### ISSUE TITLE
Script Error ??

### ISSUE THREAD

**Issue by Neogrey** [Sinap/plugin.video.funimation#2]
19:30:01 T:139855558866880   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
19:30:01 T:139854757717760    INFO: Python script stopped
19:30:01 T:139854757717760   DEBUG: Thread LanguageInvoker 139854757717760 terminating
19:30:01 T:139854518163200   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
19:30:01 T:139855558866880   ERROR: GetDirectory - Error getting plugin://plugin.video.funimation/
19:30:01 T:139855558866880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funimation/) failed
19:30:01 T:139855558866880   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/video/)
19:30:01 T:139855558866880   DEBUG:   ParentPath = []
19:30:01 T:139854757717760  NOTICE: Thread BackgroundLoader start, auto delete: false
19:30:01 T:139854757717760   DEBUG: Thread BackgroundLoader 139854757717760 terminating
19:30:01 T:139855558866880   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
19:30:04 T:139855558866880   DEBUG: ProcessMouse: trying mouse action leftclick
19:30:04 T:139855558866880   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.funimation/)
19:30:04 T:139855558866880   DEBUG:   ParentPath = [addons://sources/video/]
19:30:04 T:139854201485056   DEBUG: StartScript - calling plugin Funimation('plugin://plugin.video.funimation/','2','')
19:30:04 T:139854201485056   DEBUG: WaitOnScriptResult - waiting on the Funimation (id=3) plugin...
19:30:04 T:139854757717760  NOTICE: Thread LanguageInvoker start, auto delete: false
19:30:04 T:139854757717760    INFO: initializing python engine.
19:30:04 T:139854757717760   DEBUG: CPythonInvoker(3, /home/patrik/.kodi/addons/plugin.video.funimation-master/default.py): start processing
19:30:04 T:139854757717760  NOTICE: -->Python Interpreter Initialized<--
19:30:04 T:139854757717760   DEBUG: CPythonInvoker(3, /home/patrik/.kodi/addons/plugin.video.funimation-master/default.py): the source file to load is "/home/patrik/.kodi/addons/plugin.video.funimation-master/default.py"
19:30:04 T:139854757717760   DEBUG: CPythonInvoker(3, /home/patrik/.kodi/addons/plugin.video.funimation-master/default.py): setting the Python path to /home/patrik/.kodi/addons/plugin.video.funimation-master:/home/patrik/.kodi/addons/script.common.plugin.cache/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0:/usr/lib/python2.7/dist-packages/ubuntu-sso-client:/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode
19:30:04 T:139854757717760   DEBUG: CPythonInvoker(3, /home/patrik/.kodi/addons/plugin.video.funimation-master/default.py): entering source directory /home/patrik/.kodi/addons/plugin.video.funimation-master
19:30:04 T:139854757717760   DEBUG: CPythonInvoker(3, /home/patrik/.kodi/addons/plugin.video.funimation-master/default.py): instantiating addon using automatically obtained id of "plugin.video.funimation" dependent on version 2.1.0 of the xbmc.python api
19:30:05 T:139855558866880   DEBUG: ------ Window Init (DialogBusy.xml) ------
19:30:05 T:139855558866880   DEBUG: ------ Window Init (Pointer.xml) ------
19:30:06 T:139854757717760   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 111] Connection refused>
                                            Traceback (most recent call last):
                                              File "/home/patrik/.kodi/addons/plugin.video.funimation-master/default.py", line 26, in <module>
                                                api = Api()
                                              File "/home/patrik/.kodi/addons/plugin.video.funimation-master/resources/lib/api.py", line 34, in **init**
                                                self.login()
                                              File "/home/patrik/.kodi/addons/plugin.video.funimation-master/resources/lib/api.py", line 50, in login
                                                self._login()
                                              File "/home/patrik/.kodi/addons/plugin.video.funimation-master/resources/lib/api.py", line 59, in _login
                                                passwd, 'sessionid': self._get_session()}
                                              File "/home/patrik/.kodi/addons/plugin.video.funimation-master/resources/lib/api.py", line 137, in _get_session
                                                return self.get('phunware/system/connect.json', False)['sessid']
                                              File "/home/patrik/.kodi/addons/plugin.video.funimation-master/resources/lib/core.py", line 38, in get
                                                return self._request(endpoint)
                                              File "/home/patrik/.kodi/addons/plugin.video.funimation-master/resources/lib/core.py", line 54, in _request
                                                content = self.open(url).read()
                                              File "/usr/lib/python2.7/urllib2.py", line 404, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 422, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
                                                return self.do_open(httplib.HTTPSConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 111] Connection refused>
                                            -->End of Python script error report<--

**Comment by Neogrey** [comment]
Seems there was a problem with the server (Funimation), now it works.
